
# 应用配置
app:
  name: "public_project"
  env: "dev"  # development, testing, production
  port: 8080
  log_level: "info"


# MySQL 数据库配置
mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "123456"
  dbname: "project"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10     # 最大空闲连接数
  max_open_conns: 100    # 最大打开连接数
  conn_max_lifetime: 3600 # 连接最大生命周期(秒)
  conn_max_idle_time: 600 # 连接最大空闲时间(秒)

# Redis 配置
redis:
  host: 127.0.0.1
  port: 6379
  password: ""           # 密码，没有则为空
  db: 0                  # 数据库编号
  pool_size: 20          # 连接池大小
  min_idle_conns: 5      # 最小空闲连接数
  max_retries: 3         # 最大重试次数
  dial_timeout: 5        # 连接超时(秒)
  read_timeout: 3        # 读取超时(秒)
  write_timeout: 3       # 写入超时(秒)
  idle_timeout: 300      # 空闲连接超时(秒)

# JWT 配置
jwt:
  secret: "your-jwt-secret-key-change-in-production"
  expires_in: 3600       # token 过期时间(秒)
  refresh_expires_in: 604800 # 刷新token过期时间(秒)